Name:           ros-jade-warehouse-ros
Version:        0.9.0
Release:        0%{?dist}
Summary:        ROS warehouse_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/warehouse_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-pluginlib
Requires:       ros-jade-roscpp
Requires:       ros-jade-rostime
Requires:       ros-jade-std-msgs
Requires:       ros-jade-tf
BuildRequires:  gtest-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-rostime
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-tf

%description
Persistent storage of ROS messages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Jun 20 2016 Ioan Sucan <isucan@google.com> - 0.9.0-0
- Autogenerated by Bloom

* Sun May 31 2015 Ioan Sucan <isucan@google.com> - 0.8.8-1
- Autogenerated by Bloom

* Tue May 12 2015 Ioan Sucan <isucan@google.com> - 0.8.8-0
- Autogenerated by Bloom

