Name:           ros-melodic-warehouse-ros
Version:        0.9.1
Release:        0%{?dist}
Summary:        ROS warehouse_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/warehouse_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-pluginlib >= 1.11.2
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rostime
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
BuildRequires:  gtest-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-pluginlib >= 1.11.2
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rostime
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf

%description
Persistent storage of ROS messages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Oct 17 2018 Ioan Sucan <isucan@google.com> - 0.9.1-0
- Autogenerated by Bloom

* Mon Apr 02 2018 Ioan Sucan <isucan@google.com> - 0.9.0-0
- Autogenerated by Bloom

